### ISSUE TITLE
Invoice subscription via r_hash fails

### ISSUE THREAD

**Issue by hieblmi** [hieblmi/go-host-lnaddr#14]
Hi @rkfg, 

I recently ran into an issue that seems to be preventing the invoice subscription via the invoice r_hash you added.
This prevents the notification code from being triggered. This issue seemingly appeared without code changes from my end.
When `/v2/invoices/subscribe` is run the invoice subscription response indicates `&{Status:404 Not Found StatusCode:404......`

If you got a minute could you confirm if notifications are working for you? I could send you test payments to your lightningaddress.

**Comment by rkfg** [comment]
Hi! Yes, I've just received your payment and got a notification. 
![Screenshot_20220123-203833](https://user-images.githubusercontent.com/184066/150690789-ece94d2a-e17a-4714-9a3e-3eaf6b4aadb2.png)
Not sure what the problem could be. You might want to add more debug information to see if the invoice is generated correctly and also try to subscribe to it manually using curl. It's not really easy as you need to encode the hash as base64 and also replace some characters so it's best to start with as much debug info as possible.

**Comment by hieblmi** [comment]
Thanks for your response. I was debugging the r_hash and see that it is passed to the invoice subscription method base64 encoded which doesn't seem to be found in the existing invoices.

Do you recall which version you are running? Which is the commit you are running on?

**Comment by rkfg** [comment]
I'm on 507ac8ab764bea4fc0926b8c5f1e21ac2365d784, haven't updated since my last PR.

**Comment by hieblmi** [comment]
I am starting to believe it's my lnd installation or something. When I log an r_hash like `5YUKNOJ8ZRj7xvMPvrNtK8El8pYgSxuHCv_rDuf_Vm8=` and do a `curl -X GET --cacert /home/user/.lnd/tls.cert --header "$MACAROON_HEADER" https://localhost:8080/v2/invoices/subscribe/5YUKNOJ8ZRj7xvMPvrNtK8El8pYgSxuHCv_rDuf_Vm8=` I receive `{"code":5, "message":"Not Found", "details":[]}`.

**Comment by rkfg** [comment]
Try any manually created invoice, add one with `lncli addinvoice`, convert its payment hash to base64 and see if it works.

**Comment by hieblmi** [comment]
Nope:
```abc@ubuntu-8gb-hel1-1:~$ lncli addinvoice
{
    "r_hash": "b6220cceadda087ecbd4f47ac3ec88bcf1180d8e1e18b9f2436d3a241dbee2",
    "payment_request": "lnbc1ps7m0kcpp5kc3qenkmphdqslkt6n684slv3z70zxqd3c0p3w0jgdkn5fqahm3qdqqcqzpgxqyz5vqrzjqw260vnuwkt7l2m27kqxpq0x7nv7v5qrkyqtd44vazfteldukhn5zz4gw5qqz7sqqqqqqq
qqqqqqp9sq9qsp5nf5xsvqme0szfa72rycuvy6027xe2qadf550mqsq5uxl4s2kwqxs9qyyssqhkaa3q4uwttws7jzjvl3gwfs0y5ynn3hw9gakhm7ac2he9p06zv5hhmhdedrrqxjwuyznpq8x4xn7lf7uezgzu9rwqz2hfk3p80d5ecqh
utcjt",
    "add_index": "341",
    "payment_addr": "9a6868301bcbe024f7ca1931c6134f578d9503ad4d28fd8200a70dfac156700d"
}

abc@ubuntu-8gb-hel1-1:~$ echo b6220ccedb0dda087ecbd4f47ac3ec88bcf1180d8e1e18b9f2436d3a241dbee2 | base64
YjYyMjBjY2VkYjBkZGEwODdlY2JkNGY0N2FjM2VjODhiY2YxMTgwZDhlMWUxOGI5ZjI0MzZkM2Ey
NDFkYmVlMgo=

abc@ubuntu-8gb-hel1-1:~$ curl -X GET --cacert /home/abc/.lnd/tls.cert --header "$MACAROON_HEADER" https://localhost:8080/v2/invoices/subscribe/P+0KNfyZahh+sajK/YjYyMjBjY2VkYjBkZGE
wODdlY2JkNGY0N2FjM2VjODhiY2YxMTgwZDhlMWUxOGI5ZjI0MzZkM2Ey
{"code":5, "message":"Not Found", "details":[]}abc@ubuntu-8gb-hel1-1:~$ curl -X GET --cacert /home/abc/.lnd/tls.cert --header "$MACAROON_HEADER" https://localhost:8080/v2/invoices
/subscribe/P+0KNfyZahh+sajK/YjYyMjBjY2VkYjBkZGEwODdlY2JkNGY0N2FjM2VjODhiY2YxMTgwZDhlMWUxOGI5ZjI0MzZkM2EyNDFkYmVlMgo=
{"code":5, "message":"Not Found", "details":[]}abc@ubuntu-8gb-hel1-1:~$```

**Comment by rkfg** [comment]
You're doing it wrong! You should encode the binary value, not the hex ASCII representation. Try `echo -n 'b6220cceadda087ecbd4f47ac3ec88bcf1180d8e1e18b9f2436d3a241dbee2' | xxd -p -r | base64` (`-n` removes newline). Then replace `/` with `_` and `+` with `-` if there are any.

**Comment by hieblmi** [comment]
Thanks! Still no luck:
```
bob@ubuntu-8gb-hel1-1:~$ lncli addinvoice
{
    "r_hash": "151416051a57370962cfe9bbc0e1d5765ea0c0607215dcb7ee9ea963d11e2c3b",
    "payment_request": "lnbc1ps7msw9pp5z52pvpg62umsjck0axaupcw4we02psrqwg2aedlwn65k85g79sasdqqcqzpgxqyz5vqrzjqw260vn
uwkt7l2m27kqxpq0x7nv7v5qrkyqtd44vazfteldukhn5zz4gw5qqz7sqqqqqqqqqqqqqp9sq9qsp5cs84xmh9wud8k6m8sc6k79mtfz806zzy4heg6g
9m68e3mr9tgz2s9qyyssqkj6ml03zlff7yswe7fsrgnk7w2wglu325t3e5cmfcs0u46l6lefn3rlrvlfvh2ycppnhrc34j6g70nxq735p08ekjxw5uj3
9z2hxgxspy2n27y",
    "add_index": "344",
    "payment_addr": "c40f536ee5771a7b6b6786356f176b488efd0844adf28d20bbd1f31d8cab4095"
}

bob@ubuntu-8gb-hel1-1:~$ echo -n '151416051a57370962cfe9bbc0e1d5765ea0c0607215dcb7ee9ea963d11e2c3b' | xxd -p -r | base64
FRQWBRpXNwliz+m7wOHVdl6gwGByFdy37p6pY9EeLDs=

bob@ubuntu-8gb-hel1-1:~$ curl -X GET --cacert /home/bob/.lnd/tls.cert --header "$MACAROON_HEADER" https://localhost:
8080/v2/invoices/subscribe/FRQWBRpXNwliz-m7wOHVdl6gwGByFdy37p6pY9EeLDs=
{"code":5, "message":"Not Found", "details":[]}
```

**Comment by rkfg** [comment]
What's your `$MACAROON_HEADER`? How did you set it? Mine is set with `MACAROON_HEADER="Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ~/.lnd/data/chain/bitcoin/mainnet/invoices.macaroon)"`

**Comment by hieblmi** [comment]
`bob@ubuntu-8gb-hel1-1:~$ MACAROON_HEADER="Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 /home/bob/.lnd/data/chain/bitcoin/mainnet/invoices.macaroon)"`

**Comment by rkfg** [comment]
Since it's a weird issue there must be a weird cause... are you sure your lnd uses the same data directory? Maybe it runs under a different user or such?

**Comment by hieblmi** [comment]
You must be right, let me check it.

**Comment by rkfg** [comment]
Or maybe you run _two_ instances, one generates invoices and another listens on 127.0.0.1:8080 so of course they don't see each other. Or maybe the port is forwarded to a different host, there might be plenty of reasons like that.

**Comment by hieblmi** [comment]
Weirdly enough non of the /v2 rest endpoints seems to work. I get "Not Found" for all I tried...
`curl -X GET --cacert /home/bob/.lnd/tls.cert --header "$MACAROON_HEADER" https://localhost:8080/v2/wallet/estimatefee/3`
`{"code":5, "message":"Not Found", "details":[]}`
I wonder if I need to compile lnd with a flag for `v2`?

**Comment by rkfg** [comment]
I compile lnd with `make release BUILD_SYSTEM=linux-arm64` for my RPi node, then unpack the `.tar.gz` it produces and upload the binaries to the node. This way it includes all the flags. Maybe you forgot to include `invoicesrpc` in your tags? [Here's the full list](https://github.com/lightningnetwork/lnd/blob/master/make/release_flags.mk#L40).

**Comment by hieblmi** [comment]
That was indeed the issue. I rebuilt lnd with `make release BUILD_SYSTEM=linux-amd64` and it worked. Thanks for your help. I sent you a tip to your lightning address.

**Comment by rkfg** [comment]
Thanks, received it. I also had various issues building lnd with no tags explicitly specified, don't remember all details but many programs (RTL, lntop etc.) refused to work normally with it, most probably because of those missing APIs. After that I build using that command even though it's suboptimal as I need to unpack the result manually. Also, the binary file dates are always the same (to make the archives reproducible) so `rsync` might refuse to copy them over thinking that the files are unchanged so make sure you `touch *` them.

**Comment by hieblmi** [comment]
Pro tip! Thank you.
