### ISSUE TITLE
Doc/config discrepancy

### ISSUE THREAD

**Issue by rkfg** [hieblmi/go-host-lnaddr#21]
https://github.com/hieblmi/go-host-lnaddr/blob/ac53b9026c1fa9d720c867bb32146cdabcf18b22/config.json#L12
https://github.com/hieblmi/go-host-lnaddr/blob/ac53b9026c1fa9d720c867bb32146cdabcf18b22/main.go#L29

The parameter should be renamed to `CommentAllowed` or fixed in `README.md` and `config.json`. Otherwise the comment is silently dropped. Also this line is wrong (two commas, bad indentation): https://github.com/hieblmi/go-host-lnaddr/blob/ac53b9026c1fa9d720c867bb32146cdabcf18b22/config.json#L5

**Comment by hieblmi** [comment]
Thanks for flagging this ❤️. It should be fixed here https://github.com/hieblmi/go-host-lnaddr/pull/26
